steps:
  mtaBuild:
    buildTarget: 'NEO'
    MTA_HOME: '/opt/sap/mta/lib/mta.jar'
  neoDeploy:
    NEO_HOME: '/home/jenkins/NEO_HOME'
    neo:
      credentialsId: 'NEO_DEPLOY'
      host: 'hana.ondemand.com'
      account: 'p1942404349trial'        
